# Dockerfile.rabbitmq_initializer
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the initialization script
COPY init_rabbitmq.py /app/

# Install dependencies
RUN pip install pika==1.3.2

# Run the initialization script
CMD ["python", "init_rabbitmq.py"]